name: Build Launcher And Libraries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Launcher with Gradle
      run: ./gradlew :app:assembleRelease
    - name: Build Utils Library with Gradle
      run: ./gradlew :watchface-dev-utils:bundleReleaseAar
    - name: Build Watchface Example with Gradle
      run: ./gradlew :watchface-example:assembleRelease
    - name: Upload Launcher APK
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-debug
        path: app/build/outputs/apk/release/app-release.apk
    - name: Upload Utils AAR
      uses: actions/upload-artifact@v4
      with:
        name: watchface-dev-utils
        path: watchface-dev-utils/build/outputs/aar/watchface-dev-utils-release.aar
    - name: Upload Watchface Example
      uses: actions/upload-artifact@v4
      with:
        name: watchface-example
        path: watchface-example/build/outputs/apk/release/watchface-example-release.apk
